### PR TITLE
fix(summary): do not fallback to make summary for paywall'ed content

### LINKED ISSUE #2464: [Server] - Locked post display parts of content if summary is not set

### PR DESCRIPTION
**Pull request by tx0c**
resolves #2464

### CODE REVIEW

File: src/queries/article/summary.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+const resolver: ArticleToSummaryResolver = async (
+  parent,
+  args,
+  context,
+  info
+) => {
+  const { summary, content: cont } = parent
+  const accessType = await accessTypeResolver(parent, args, context, info)
+
+  // console.log('data:', { articleId, summary, accessType, license })
```
Comment (guoliu) [inline src/queries/article/summary.ts:17]: We can delete this?

**Review by guoliu — APPROVED** [review]
🌿
