### PR TITLE
fix: returning('id') does not return integers in knex v2.1

### LINKED ISSUE #2647: [Server] Server fails to process `invoice.payment_succeeded` Stripe event
#### Tasks
- [ ] Investigate and fix Stripe events were not handled properly

#### References
- [slack](https://mattersnews.slack.com/archives/G01KESNNH8D/p1658923201776629)

### PR DESCRIPTION
**Pull request by Carolusian**
fix #2647

### CODE REVIEW

File: src/connectors/paymentService.ts [hunk 1]
```diff
@@ -556,18 +556,16 @@ export class PaymentService extends BaseService {
           targetType: undefined,
           targetId: undefined,
         })
-        .returning('id')
+        .returning('*')
```
Comment (tx0c) [inline src/connectors/paymentService.ts:559]: this line might not be necessary? I see you'll need only `trans.id`

**Review by tx0c — COMMENTED** [review]
link to this line https://knexjs.org/changelog.html#_1-0-0-16-january-2022 in comments could be good, there might be other Breaking Changes as well:

```
Changed data structure from RETURNING operation to be consistent with SELECT;

**Review by robertu7 — APPROVED** [review]

**Comment by robertu7** [comment]
wen to merge and test?

File: src/connectors/paymentService.ts (hunk 1 above)
Comment (Carolusian) [reply src/connectors/paymentService.ts:559]: Updated to `.return('*')` because it has better compatibility, and is more consistent with the code in other places. For other code using `.return('*')`, the function is not breaking after being upgraded to knex v2.1.
