### PR TITLE
fix/ license should remain unchanged after changing other fields

### LINKED ISSUE #2359: [Server] - Support ARR license for articles

### PR DESCRIPTION
**Pull request by tx0c**
resolves #2359 [Server] - Support ARR license for articles 3 pt feature request

### CODE REVIEW

File: src/mutations/draft/putDraft.ts [hunk 1]
```diff
@@ -182,7 +181,7 @@ const resolver: MutationToPutDraftResolver = async (
       collection: collectionIds,
       circleId,
       access: accessType,
-      license: license || ARTICLE_LICENSE_TYPE.cc_by_nc_nd_2,
+      license, // : license || ARTICLE_LICENSE_TYPE.cc_by_nc_nd_2,
```
Comment (tx0c) [inline src/mutations/draft/putDraft.ts:184]: does that `null to reset` have a use case in current website?

**Review by devformatters — APPROVED** [review]

**Comment by devformatters** [comment]
I'll merge it for QA.
